### PR TITLE
documentation, linter and license scanners config update

### PR DESCRIPTION
**Pull request by hsoltysi**
README.md - expansion,
ansible inter config file update and
license scanner excludes file
update

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/benchmarking/5)

### CODE REVIEW

**Review by mmatuszek1 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/benchmarking/5)* status: all files reviewed, 2 unresolved discussions (waiting on @hsoltysi and @zemdom)

___
*[README.md, line 61 at r1](https://reviewable.io/reviews/pmem/benchmarking/5#-MhqvZqdDjWdzatnK54y:-MhqvZqdDjWdzatnK54z:bp6b40) ([raw file](https://github.com/pmem/benchmarking/blob/24cdb670b1e8a85323774de1be34eda815387c2f/README.md#L61)):*
> ```Markdown
> When you have completed all the prerequisite steps, it is time to run the benchmark. You will do it by following the steps below:  
> 
> 1. Clone the __kvm-redis__  repo to your local machine
> ```

Please update repo name (kvm-redis -> benchmarking)
___
*[README.md, line 63 at r1](https://reviewable.io/reviews/pmem/benchmarking/5#-Mhqvyj1DriWjm8jA6E4:-Mhqvyj1DriWjm8jA6E5:bp6b40) ([raw file](https://github.com/pmem/benchmarking/blob/24cdb670b1e8a85323774de1be34eda815387c2f/README.md#L63)):*
> ```Markdown
> 1. Clone the __kvm-redis__  repo to your local machine
> 
> 2. Change the directory to kvm-redis by running the command __cd kvm-redis__ 
> ```

Please update repo name (kvm-redis -> benchmarking)

**Comment by hsoltysi** [comment]
> > Reviewed 9 of 9 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/pmem/benchmarking/5)_ status: all files reviewed, 2 unresolved discussions (waiting on @hsoltysi and @zemdom)
> 
> _[README.md, line 61 at r1](https://reviewable.io/reviews/pmem/benchmarking/5#-MhqvZqdDjWdzatnK54y:-MhqvZqdDjWdzatnK54z:bp6b40) ([raw file](https://github.com/pmem/benchmarking/blob/24cdb670b1e8a85323774de1be34eda815387c2f/README.md#L61)):_
> 
> > ```gfm
> > When you have completed all the prerequisite steps, it is time to run the benchmark. You will do it by following the steps below:  
> > 
> > 1. Clone the __kvm-redis__  repo to your local machine
> > ```
> 
> Please update repo name (kvm-redis -> benchmarking)
> 
> _[README.md, line 63 at r1](https://reviewable.io/reviews/pmem/benchmarking/5#-Mhqvyj1DriWjm8jA6E4:-Mhqvyj1DriWjm8jA6E5:bp6b40) ([raw file](https://github.com/pmem/benchmarking/blob/24cdb670b1e8a85323774de1be34eda815387c2f/README.md#L63)):_
> 
> > ```gfm
> > 1. Clone the __kvm-redis__  repo to your local machine
> > 
> > 2. Change the directory to kvm-redis by running the command __cd kvm-redis__ 
> > ```
> 
> Please update repo name (kvm-redis -> benchmarking)

Done

**Review by zemdom — APPROVED** [review]

**Review by hsoltysi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/benchmarking/5)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @mmatuszek1)

___
*[README.md, line 61 at r1](https://reviewable.io/reviews/pmem/benchmarking/5#-MhqvZqdDjWdzatnK54y:-Mhwj2TnErXLge1hcNug:b-896fix) ([raw file](https://github.com/pmem/benchmarking/blob/24cdb670b1e8a85323774de1be34eda815387c2f/README.md#L61)):*
<details><summary><i>Previously, mmatuszek1 wrote…</i></summary><blockquote>

Please update repo name (kvm-redis -> benchmarking)
</blockquote></details>

Done.
___
*[README.md, line 63 at r1](https://reviewable.io/reviews/pmem/benchmarking/5#-Mhqvyj1DriWjm8jA6E4:-Mhwj53K7MCMsSVU-_YL:b-896fix) ([raw file](https://github.com/pmem/benchmarking/blob/24cdb670b1e8a85323774de1be34eda815387c2f/README.md#L63)):*
<details><summary><i>Previously, hsoltysi wrote…</i></summary><blockquote>

Done
</blockquote></details>

Done.

**Review by mmatuszek1 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/benchmarking/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hsoltysi)

**Pull request merged**
