### PR TITLE
Add scripts to run kvm-redis benchmark

### PR DESCRIPTION
**Pull request by hsoltysi**
Add scripts to run kvm-redis benchmark

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/kvm-redis/6)

### CODE REVIEW

**Review by mmatuszek1 — COMMENTED** [review]
> Reviewed 14 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/benchmarking/6)* status: 14 of 22 files reviewed, 4 unresolved discussions (waiting on @hsoltysi and @zemdom)

___
*[ansible-playbook/create.yml, line 190 at r1](https://reviewable.io/reviews/pmem/benchmarking/6#-Mi16Jhc2eLY6kcBt3gK:-Mi16Jhd9tFuQtv3z_sM:bt4b84c) ([raw file](https://github.com/pmem/benchmarking/blob/856cc0946bf28c053e9d2bd8274d12dc92840e9f/ansible-playbook/create.yml#L190)):*
> ```YAML
>               - "5000:5000"
>             auto_remove: true
>             network_mode: "host"
> ```

not required when exposing ports and may cause errors
___
*[ansible-playbook/run-benchmark.yml, line 223 at r1](https://reviewable.io/reviews/pmem/benchmarking/6#-Mi17SBu26rESx0mtLCW:-Mi17SBu26rESx0mtLCX:b944u7t) ([raw file](https://github.com/pmem/benchmarking/blob/856cc0946bf28c053e9d2bd8274d12dc92840e9f/ansible-playbook/run-benchmark.yml#L223)):*
> ```
> --key 2 
> ```
column number is not required in that command, same below
___
*[ansible-playbook/include/create-configdrives.yml, line 0 at r1](https://reviewable.io/reviews/pmem/benchmarking/6#-Mi18LAF9MwwTE29MbRn:-Mi18LAF9MwwTE29MbRo:b29ytha) ([raw file](https://github.com/pmem/benchmarking/blob/856cc0946bf28c053e9d2bd8274d12dc92840e9f/ansible-playbook/include/create-configdrives.yml#L0)):*
remove that file
___
*[ansible-playbook/templates/dhcpd.conf.j2, line 1 at r1](https://reviewable.io/reviews/pmem/benchmarking/6#-Mi19JM0-1rqvHv4jG4W:-Mi19JM0-1rqvHv4jG4X:bbbvh15) ([raw file](https://github.com/pmem/benchmarking/blob/856cc0946bf28c053e9d2bd8274d12dc92840e9f/ansible-playbook/templates/dhcpd.conf.j2#L1)):*
> ```Jinja
> # SPDX-License-Identifier: BSD-3-Clause
> ```

I can be wrong but it's incorrect way of commenting in jinja. The same regards other templates.

**Review by zemdom — APPROVED** [review]

**Review by adam-ad — APPROVED** [review]
lgtm

**Review by mmatuszek1 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 22 files at r1, 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/kvm-redis/6#-:-MsE68i3DGOTfqseEM8D:bnfp4nl)* status: 26 of 27 files reviewed, 4 unresolved discussions (waiting on @hsoltysi and @mmatuszek1)

**Review by mmatuszek1 — APPROVED** [review]
> Reviewed 1 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/kvm-redis/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hsoltysi)

**Pull request merged**
